name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    FORCE_COLOR: true
    NODE_OPTIONS: "--max-old-space-size=1536"

jobs:
    test:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: pnpm install --frozen-lockfile --network-concurrency 1 --store-dir /opt/pnpm-store

            - name: Build & Lint & Type-check
              run: pnpm test

            - name: Test web build
              run: pnpm buildWeb --no-bundle-buddy
