name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    FORCE_COLOR: true
    NODE_OPTIONS: "--max-old-space-size=2048"

jobs:
    test:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  export PNPM_HOME="/home/runner/.local/share/pnpm"
                  export PATH="$PNPM_HOME:$PATH"
                  pnpm install --frozen-lockfile
              env:
                  # Reduce pnpm concurrency to lower peak memory usage
                  PNPM_WORKERS: 2

            - name: Build & Lint & Type-check
              run: |
                  export PNPM_HOME="/home/runner/.local/share/pnpm"
                  export PATH="$PNPM_HOME:$PATH"
                  pnpm test

            - name: Test web build
              run: |
                  export PNPM_HOME="/home/runner/.local/share/pnpm"
                  export PATH="$PNPM_HOME:$PATH"
                  pnpm buildWeb
